import os

WINDOW_WIDTH = 800
WINDOW_HEIGHT = 600

BASE_DIR = os.path.os.path.dirname(__file__)

SCENES_PATH = BASE_DIR + '/Scene/'
MAIN_SCENE_PATH = {
    'name': 'Main',
    'path': SCENES_PATH + 'Main.jpeg',
}
SCENES = [
    {
        'name': 'Fog',
        'path': SCENES_PATH + 'Fog.jpeg',
        'char_position':[400, 530]
    },{
        'name': 'Clear',
        'path': SCENES_PATH + 'Clear.jpeg',
        'char_position':[400, 410]
    },{
        'name': 'Clouds',
        'path': SCENES_PATH + 'Clouds.jpeg',
        'char_position':[400, 460]
    },{
        'name': 'Drizzle',
        'path': SCENES_PATH + 'Drizzle.jpeg',
        'char_position':[400, 440]
    },{
        'name': 'Rain',
        'path': SCENES_PATH + 'Rain.jpeg',
        'char_position':[400, 390]
    },{
        'name': 'Thunderstorm',
        'path': SCENES_PATH + 'Thunderstorm.jpeg',
        'char_position':[400, 500]
    }
]

HEALTH_OFFSET = -100
HEALTHBAR_LENGTH = 80
HEALTHBAR_HEIGHT = 20
HEALTHBAR_COLORS = ['red3', 'red', 'orange red', 'orange', 'gold',
                    'yellow', 'green yellow', 'lawn green', 'spring green',
                    'green2', 'green2']
HEALTHBAR_BG_COLOR = 'grey50'
HEALTH_TEXT_COLOR = 'black'

GAME_FONT = 'Monaco'
GAME_FONT_RATIO = 0.43 / 0.75

BUTTON_BG_COLOR = 'black'
MAIN_BUTTON_WIDTH = 260
MAIN_BUTTON_HEIGHT = 40
BUTTON_LOOK = 'flat'
BUTTON_FONT_SIZE = 20
BUTTTON_FONT_COLOR = 'white'
BUTTON_SPACING = MAIN_BUTTON_HEIGHT / 4

HEADER_FONT_SIZE = 30
HEADER_Y_COORD = 50

PADDING = 20

MENU_BG_COLOR = 'wheat2'

BUTTON_WIDTH = 76
BUTTON_HEIGHT = 36

# ===== CHARACTER MENU CONSTANTS =====

CHAR_MENU_WIDTH = 440
CHAR_MENU_HEIGHT = 300
STATS_WIDTH = 164
STATS_HEIGHT = 200

CHAR_MENU_X_START = int(WINDOW_WIDTH / 2 - CHAR_MENU_WIDTH / 2)
CHAR_MENU_Y_START = int(WINDOW_HEIGHT / 2 - CHAR_MENU_HEIGHT / 2)
CHAR_MENU_X_END = CHAR_MENU_X_START + CHAR_MENU_WIDTH
CHAR_MENU_Y_END = CHAR_MENU_Y_START + CHAR_MENU_HEIGHT
# CENTER_BUTTON_X_COORD = WINDOW_WIDTH / 2 - int(BUTTON_WIDTH / 2)
# CENTER_BUTTON_Y_COORD = CHAR_MENU_Y_END - BUTTON_HEIGHT - PADDING
STATS_X_COORD = CHAR_MENU_X_START + int(STATS_WIDTH / 2) + PADDING
STATS_Y_COORD = CHAR_MENU_Y_START + int(STATS_HEIGHT / 2) + PADDING
CHAR_X_COORD = CHAR_MENU_X_END - PADDING - 100 + 50
CHAR_Y_COORD = CHAR_MENU_Y_START + PADDING + 100
CHAR_BG_COLOR = 'royal blue'

# ===== NEW GAME MENU CONSTANTS ======

ENTER_NAME_TEXT = "Enter Cat's Name"
CHOOSE_CLASS_TEXT = "Choose Cat's Class"
NEW_GAME_MENU_WIDTH = 300
NEW_GAME_MENU_HEIGHT = 260

ENTRY_WIDTH = 162
TEXT_HEIGHT = 18
LIST_WIDTH = 162
BUTTON_WIDTH_CHARS = 8
BUTTON_HEIGHT_CHARS = 2

NEW_GAME_MENU_X_START = int(WINDOW_WIDTH / 2 - NEW_GAME_MENU_WIDTH / 2)
NEW_GAME_MENU_Y_START = int(WINDOW_HEIGHT / 2 - NEW_GAME_MENU_HEIGHT / 2)
NEW_GAME_MENU_X_END = NEW_GAME_MENU_X_START + NEW_GAME_MENU_WIDTH
NEW_GAME_MENU_Y_END = NEW_GAME_MENU_Y_START + NEW_GAME_MENU_HEIGHT
TEXT_X_COORD = int(WINDOW_WIDTH / 2)
NAME_TEXT_Y_COORD = NEW_GAME_MENU_Y_START + PADDING
CLASS_TEXT_Y_COORD = NAME_TEXT_Y_COORD + 60
ENTRY_X_COORD = int(WINDOW_WIDTH / 2 - ENTRY_WIDTH / 2)
ENTRY_Y_COORD = NAME_TEXT_Y_COORD + int(TEXT_HEIGHT / 2)
LIST_X_COORD = int(WINDOW_WIDTH / 2 - ENTRY_WIDTH / 2)
LIST_Y_COORD = CLASS_TEXT_Y_COORD + int(TEXT_HEIGHT / 2)
# LEFT_BUTTON_X_COORD = NEW_GAME_MENU_X_START + PADDING
# LEFT_BUTTON_Y_COORD = NEW_GAME_MENU_Y_END - BUTTON_HEIGHT - PADDING
# RIGHT_BUTTON_X_COORD = NEW_GAME_MENU_X_END - BUTTON_WIDTH - PADDING
# RIGHT_BUTTON_Y_COORD = LEFT_BUTTON_Y_COORD

# ===== SAVE SLOTS CONSTANTS =====

SLOT_MENU_HEIGHT = 340
SLOT_MENU_WIDTH = 400
SLOT_HEIGHT = 40
SLOT_WIDTH = SLOT_MENU_WIDTH - 42
SLOT_MENU_X_START = int(WINDOW_WIDTH / 2 - SLOT_MENU_WIDTH / 2)
SLOT_MENU_Y_START = int(WINDOW_HEIGHT / 2 - SLOT_MENU_HEIGHT / 2)
SLOT_MENU_X_END = SLOT_MENU_X_START + SLOT_MENU_WIDTH
SLOT_MENU_Y_END = SLOT_MENU_Y_START + SLOT_MENU_HEIGHT

# ===== LOCATION MENU CONSTANTS =====

LOC_INPUT_WIDTH = 19
LOC_TEXT = 'Enter City Name:'
LOC_MENU_WIDTH = 320
LOC_MENU_HEIGHT = 300
LOC_MENU_X_START = int(WINDOW_WIDTH / 2 - LOC_MENU_WIDTH / 2)
LOC_MENU_Y_START = int(WINDOW_HEIGHT / 2 - LOC_MENU_HEIGHT / 2)
LOC_MENU_X_END = LOC_MENU_X_START + LOC_MENU_WIDTH
LOC_MENU_Y_END = LOC_MENU_Y_START + LOC_MENU_HEIGHT
LOC_TEXT_X_COORD = int(WINDOW_WIDTH / 2)
LOC_TEXT_Y_COORD = LOC_MENU_Y_START + PADDING + TEXT_HEIGHT / 2

# ===== FIGHT SCREEN CONSTANTS =====

DEFEND_PROMPT = 'DEFEND!'
ATTACK_PROMPT = 'ATTACK!'

ENDGAME_MESSAGE_WIDTH = 150
ENDGAME_MESSAGE_HEIGHT = 100
WIN_MESSAGE = 'YOU HAVE WON!'
LOSE_MESSAGE = 'YOU HAVE LOST'

ATTACK_STATUS_COLOR = 'firebrick4'
